2021_05_31.md, 2021_06_21.md
I'm happy to make changes, just let me know how I can help.
=> Additional notes on 5-31 and 6-21

README.md
Thanks for putting on these on, I really enjoy listening in.
=> Video link for Aug 16 2021

2021_09_06.md
- Fix SMR and Smart NIC links and add context
- Add @ahl's point about Optane's lack of economic niche
- Add cool sound bite from @jclulow
=> Clarify discussion: backwards compatibility vs. marginal gains

2022_01_03.md
Ah do we add a table for each prediction, or just a row? :P
=> Add @tinco's predictions

2022_01_03.md
Though browsers are quite tolerant, tags feel better when closed. :-)
=> 2022 predictions: fix links, add timestamp for Ben

2022_01_03.md
These are not mine, but I like Aaron's "microservices inlining" prediction so much I tried to paraphrase it here.
=> Add Aaron Goldman's predictions

README.md
=> Add RSS-Feed to Readme

2022_04_18.md
Added annotations to the Twitter spaces notes of 2022_04_18
=> added annotations to 2022_04_18.md

2022_06_20.md
Line 14 is a paste artifact, please delete.
=> added annotations for 2022_06_20

2022_07_18.md
For #69.
-----
(still working through this episode 🙂)
=> 7/18: notes and links for the first half hour

2022_08_01.md
Thanks for hosting and publishing these talks!
=> Adding link to image and quick notes

2023_01_09.md
I can add the YT timestamp later once it exists.
=> Add @tfpk's predictions.

2023_01_09.md
Joining in the fun with my terrible predictions.
=> Please add my predictions

2023_01_09.md
Similarly waiting for the recording to add my timestamp
(also if you want more glossary I can do that)
=> Add my predictions

2023_01_23.md
Add timestamps and links for the January 23rd episode.
=> Add some notes for 2023-01-23

2023_02_27.md
I actually think this is quite the testimonial!
Quote appears at 1:01:21 in the audio.
=> Add Adam's codegen quote

2023_03_27.md
I listened to the whole show but missed what Andrew was saying about how he built the TUI. Gave it another quick listen now to find this info; maybe it will help others
=> Note technology used to create TUI described

2022_07_18.md
Hopefully this is not unwelcome - I was listening to this episode from 9 months ago and saw it had incomplete notes, so took down notes and found links for them.  If this is unlikely to be valuable at this point and would just require work from a reviewer for little gain, I'd understand if you just closed this.
=> show notes for the rest of 2022-07-18

2022_09_26.md
What to put here... Have some notes!
=> add show notes for 2022-09-26

2022_10_10.md
Notes and I think I identified most of the speakers.
=> notes for 2022-10-10

2022_10_03.md
To you good people, I offer more notes.
My branch name is the bungle, not the date in the repo.
I feel like the style has been slightly different each time I've done this.  This time, I tried to follow the style in the current template, even though this is an older show.  I'm more than happy for feedback on that approach, and can retouch the styling if desired.
=> add notes for mis/incentives show

2023_05_30.md
Thanks to @bcantrill for linking me to the talk!  It was indeed excellent!
=> docs: 2023-05-30 updates

2022_11_28.md
Added some timestamps, fixed ordering, and added more notes.
=> more show notes for 2022-11-28 show

2022_11_14.md
There were a bunch of speakers and I caught some names, but with very low confidence, so I didn't attempt to fill those in.
=> notes for mastadon show

2022_11_07.md
Have some more notes.
I suppose I should offer to consolidate MRs in the future.  Would adding new commits to an existing branch/MR for a second show be preferable?
=> notes for tech layoffs show

2022_10_31.md
=> add show notes for open source firmware

2022_10_27_special.md
Very difficult to refrain from inserting omniscient narrator voice from after the fact.
=> twitter notes

2022_10_24.md
=> provide more show notes for 2022-10-24

2023_07_03.md
Adds timestamps to all questions and summaries/key quotes of the answers.
Adds some Qs that were missing from the notes, though I'm unable to
provide links to those.
Thanks for the great podcast!
=> 2023-07-03: Add timestamps and answers

2023_07_24.md
Some extra books mentioned near the end of the podcast
=> Adding more books

2023_07_10.md
Mendes like Sergio Mendes or Eva Mendes, yes people often bring me up when talking about these creative people
=> fixed Mendes spelling

LICENSE
=> Add CC-BY-4.0 license

2024_01_08.md
These were in discord chat, didn't make the recording.
=> Add 2024 predictions

2024_01_15.md
=> add blog post

2021_06_07.md, 2021_08_16.md, 2021_10_18.md, 2022_02_14.md, 2022_03_07.md, 2022_04_18.md, 2022_07_18.md, 2022_09_26.md, 2022_10_27_special.md, 2022_10_31.md, 2023_01_09.md, 2023_02_13.md, 2023_02_27.md, 2023_03_20.md, 2023_03_27.md, 2023_05_01.md, 2023_07_03.md, 2023_08_28.md
Noticed a typo, so I ran `codespell` and found a bunch more.
=> fix spelling

2024_02_12.md
Some people listening to the episode may be encountering the concept of backpressure for the first time, so I've added links to some articles explaining it.
Also, visual evidence that "God's own backpressure" is not a new phrase for Bryan. :smile:
=> Added links about backpressure

2024_03_04.md
This should either be helpful for others *or* at least speed up their falling down rabbit holes.
=> Added notes for 2024-03-04

2024_04_01.md
Microarch.club seems to be the exact kind of podcast I have been searching for a long time. I am starting to listen to it now. And I would like other OxF listeners to go listen to it.
=> Update 2024_04_01.md to include Microarch.club episode

2024_01_22.md
The link is pointing to the correct book with the correct creature on the cover.  Corrected the name of the creature in the show notes.
=> Fix book animal

2024_07_08.md
Adds the (Amazon) link to the [Skunk Works: A Personal Memoir of My Years at Lockheed](https://www.amazon.com/Skunk-Works-Personal-Memoir-Lockheed/dp/0316743003) book.
=> add link to the Skunk Works book

2024_07_15.md
More notes on "Heterogeneous computing with Raja Koduri"
=> Notes on Heterogeneous computing with Raja Koduri

2024_10_28.md
Thanks for having me! Here's my blue-sky.
=> Add blue-sky for Nick

2024_11_18.md, README.md
=> November 18th's Shownotes

2025_01_06.md
Adds my predictions. I will not be able to make the episode live, but I'd love to hear discussion on my 3 year.
=> My predictions.

2025_01_06.md
Forgot to raise this PR a few weeks ago!
=> Add 2025 Predictions

2025_02_24.md
Not labelled as a Big Theory Statement, but it's still in illumos-gate HEAD.
=> 2025-02-24: Link divide by 1 billion comment

2025_03_03.md
=> Add proc macro tutorial link

2025_02_10.md
* Fix jclulow bsky link
* Add curses, ncurses, X11 books, battletris, crossterm, trunk-rs, masonry, xilem
=> 2025-02-10: Add/fix links
